# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  paths-ignore:
    - 'README.md'
    - 'docs/**'
    - '*.md'
jobs:

  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Create bin directory
      run: mkdir bin
    
    - name: Build
      run: go build -v -o bin/myapp.exe ./main.go  # 明确指定入口文件
    
    - name: Verify executable exists
      run: dir bin\  # Windows下查看目录内容
    
    - name: Test
      run: go test -v ./...

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: ./bin/myapp.exe 